-- SAVI Supabase/PostgreSQL schema
-- Run in the Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS public.braceletes (
    esp_id          INTEGER          PRIMARY KEY,
    em_uso          BOOLEAN          NOT NULL DEFAULT FALSE,
    temperatura     REAL,
    bpm             SMALLINT,
    spo2            SMALLINT,
    acc_x           REAL,
    acc_y           REAL,
    acc_z           REAL,
    gyro_x          REAL,
    gyro_y          REAL,
    gyro_z          REAL,
    atualizado_em   TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.alertas (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    esp_id      INTEGER      NOT NULL REFERENCES public.braceletes (esp_id)
                              ON UPDATE CASCADE ON DELETE RESTRICT,
    tipo        VARCHAR(32)  NOT NULL,
    valor       REAL         NOT NULL,
    criado_em   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alertas_esp_id ON public.alertas (esp_id);
CREATE INDEX IF NOT EXISTS idx_alertas_tipo ON public.alertas (tipo);

-- ID pool. em_uso=false means the gateway may assign the ID.
INSERT INTO public.braceletes (esp_id, em_uso) VALUES
    (1, FALSE),
    (2, FALSE),
    (3, FALSE),
    (4, FALSE),
    (5, FALSE),
    (6, FALSE),
    (7, FALSE),
    (8, FALSE)
ON CONFLICT (esp_id) DO NOTHING;

-- Configure Supabase grants and RLS policies for the anon role separately.
-- Permit SELECT and UPDATE on public.braceletes, and INSERT on public.alertas.
